on:
      push:
        branches:
            - main

jobs:
    job1:
        runs-on: ubuntu-latest 
        outputs:
            artifact: my-app
        steps:
            - id: step1
              name: step 1
              run: echo "tip=hello >> $GITHUB_OUTPUT 
            - name: stp 2
              run: echo "output from step1 is ${{ steps.step1.outputs.tip}}"
    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ needs.job1.outputs.artifact }}"                     